apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  labels:
    app: {{ include "backstage.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backstage.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backstage.name" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backstage
          image: ghcr.io/vpydikondala/backstage:latest
          command:
            - "uvicorn"
            - "app.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "7007"
          ports:
            - containerPort: 7007
          livenessProbe:
            httpGet:
              path: /health
              port: 7007
            initialDelaySeconds: 30  # Delay before starting the probe
            periodSeconds: 10  # Frequency of the probe
            timeoutSeconds: 5  # Timeout for each probe
            failureThreshold: 3  # Number of failed probes before the container is considered unhealthy
          readinessProbe:
            httpGet:
              path: /health
              port: 7007
            initialDelaySeconds: 5  # Delay before starting the probe
            periodSeconds: 5  # Frequency of the probe
            timeoutSeconds: 5  # Timeout for each probe
            failureThreshold: 3  # Number of failed probes before considering the container not ready
          env:
            - name: BACKSTAGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            # Add other environment variables as needed
