apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backstage.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backstage.name" . }}
        {{- include "backstage.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backstage
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: BACKSTAGE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.name }}
                  key: {{ .Values.secrets.database.key }}
            - name: GITHUB_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.githubPAT.name }}
                  key: {{ .Values.secrets.githubPAT.key }}
            - name: GITHUB_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.githubOAuth.name }}
                  key: {{ .Values.secrets.githubOAuth.clientIdKey }}
            - name: GITHUB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.githubOAuth.name }}
                  key: {{ .Values.secrets.githubOAuth.clientSecretKey }}
            {{- if .Values.secrets.argocdToken.enabled }}
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.argocdToken.name }}
                  key: {{ .Values.secrets.argocdToken.key }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
      volumes:
        - name: config
          configMap:
            name: app-config
