{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "svc.fullname" . }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range $h := .Values.ingress.hosts }}
    - host: {{ $h.host | quote }}
      http:
        paths:
          {{- range $p := $h.paths }}
          - path: {{ $p.path | default "/" }}
            pathType: {{ $p.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "svc.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
