# templates/microservice-fastapi/skeleton/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-fastapi
  title: FastAPI Microservice Template
  description: Scaffold a FastAPI app with Helm, Docker, ArgoCD, GitHub Actions
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Provide service metadata
      required: [name]
      properties:
        name:
          type: string
          title: Name
          description: The name of the microservice
  steps:
    - id: fetch-base
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./templates/microservice-fastapi/skeleton
        values:
          name: ${{ parameters.name }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?repo=${{ parameters.name }}&owner=<your-org>
        defaultBranch: main
        description: Scaffolding a FastAPI microservice
    - id: register
      name: Register with Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/environments/dev/argocd/catalog-info.yaml'
