yarnPath: .yarn/releases/yarn-4.9.4.cjs

# Backstage prefers node-modules linker
nodeLinker: node-modules

# Ensure we fetch public Backstage packages from npmjs (not a private feed)
npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  backstage:
    npmRegistryServer: "https://registry.npmjs.org"
  spotify:
    npmRegistryServer: "https://registry.npmjs.org"
