nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  backstage:
    npmRegistryServer: "https://registry.npmjs.org"
  spotify:
    npmRegistryServer: "https://registry.npmjs.org"
