replicaCount: 1

image:
  repository: ghcr.io/vpydikondala/backstage-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []   # e.g. - name: ghcr-creds

service:
  port: 80
  targetPort: 7007

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
