replicaCount: 1

image:
  repository: ghcr.io/{{ ghOrg }}/{{ name }}
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: {{ host }}
      paths:
        - path: /
          pathType: Prefix
