# helm-chart/values.tpl.yaml
# Rendered by Terraform templatefile()

# --- Service exposure via Ingress (NGINX) ---
ingress:
  enabled: true
  # single host, not an array
  host: "${backstage_host}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  # object, not an array
  tls:
    enabled: false
    secretName: ""   # set if you terminate TLS at the ingress (AKS + cert-manager etc.)

# --- Kubernetes Service (schema uses 'ports' object) ---
service:
  type: ClusterIP
  ports:
    name: "http-backend"
    backend: 7007
    targetPort: "backend"

# --- Backstage container wiring ---
backstage:
  # name the container port 'backend' so targetPort above can reference it
  containerPorts:
    backend: 7007
  # easiest way to keep Backstage baseUrls in sync with your ingress host
  extraEnvVars:
    - name: APP_CONFIG_app_baseUrl
      value: "http://${backstage_host}"
    - name: APP_CONFIG_backend_baseUrl
      value: "http://${backstage_host}"
    - name: APP_CONFIG_backend_cors_origin
      value: "http://${backstage_host}"

# --- Image coordinates (ACR) ---
image:
  repository: "${acr_name}.azurecr.io/backstage"
  tag: "${image_tag}"
  pullPolicy: IfNotPresent

# --- Postgres managed by the chart (optional) ---
postgresql:
  enabled: true
  auth:
    username: backstage
    password: "${pg_password}"
    database: backstage
