service:
  type: LoadBalancer
  ports:
    http: 80

appConfig:
  app:
    baseUrl: http://<PUBLIC_IP>
  backend:
    baseUrl: http://<PUBLIC_IP>/api
    listen:
      port: 7007
      basePath: /api
  database:
    client: pg
    connection:
      host: backstage-postgresql
      port: 5432
      user: backstage
      password: myStrongPostgresPassword
      database: backstage

backend:
  image:
    repository: youracr.azurecr.io/backstage
    tag: latest
    pullPolicy: IfNotPresent

postgresql:
  enabled: true
  auth:
    username: backstage
    password: myStrongPostgresPassword
    database: backstage
