apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ name }}
  description: FastAPI service scaffolded by Backstage
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: {{ ghOrg }}/{{ name }}
    argocd/app-name: {{ name }}-app
    backstage.io/kubernetes-id: {{ name }}
    backstage.io/kubernetes-namespace: {{ namespace }}
spec:
  type: service
  owner: group:team-product
  system: product-platform
  lifecycle: experimental
