apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservice-fastapi
  description: FastAPI microservice for Backstage IDP PoC
spec:
  type: service
  lifecycle: experimental
  owner: team@example.com
  system: backstage-idp-poc
  providesApis:
    - my-api
  consumesApis: []
  dependsOn:
    - resource:postgresql
  implementsApis: []
