apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/{{ ghOrg }}/{{ name }}.git
    targetRevision: main
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
